In [1]:
# Based on Stevens et al. Deep learning with PyTorch, Manning Publications Co, 2020

import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [5]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
points.shape

torch.Size([3, 2])

In [10]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[0, 1]

tensor(1.)

In [13]:
points[0]

tensor([4., 1.])