In [6]:
# Based on Stevens et al. Deep learning with PyTorch, Manning Publications Co, 2020

import numpy as np
import torch
torch.set_printoptions(edgeitems=2, precision=2, linewidth=75)

In [30]:
import csv
wine_path = "../Exercise_05/wine.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=",", skiprows=1)
wineq_numpy

array([[1.000e+00, 1.423e+01, 1.710e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.000e+00, 1.320e+01, 1.780e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.000e+00, 1.316e+01, 2.360e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [3.000e+00, 1.327e+01, 4.280e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [3.000e+00, 1.317e+01, 2.590e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [3.000e+00, 1.413e+01, 4.100e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], dtype=float32)

In [31]:
col_list = next(csv.reader(open(wine_path), delimiter=','))

wineq_numpy.shape, col_list

((178, 14),
 ['Wine',
  'Alcohol',
  'Malic.acid',
  'Ash',
  'Acl',
  'Mg',
  'Phenols',
  'Flavanoids',
  'Nonflavanoid.phenols',
  'Proanth',
  'Color.int',
  'Hue',
  'OD',
  'Proline'])

In [35]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

(torch.Size([178, 14]), torch.float32)

In [36]:
data = wineq[:, :-1] # <1>
data, data.shape

(tensor([[ 1.00, 14.23,  ...,  1.04,  3.92],
         [ 1.00, 13.20,  ...,  1.05,  3.40],
         ...,
         [ 3.00, 13.17,  ...,  0.60,  1.62],
         [ 3.00, 14.13,  ...,  0.61,  1.60]]),
 torch.Size([178, 13]))

In [44]:
target = wineq[:, -1] # <2>
target, target.shape

(tensor([1065., 1050., 1185., 1480.,  735., 1450., 1290., 1295., 1045.,
         1045., 1510., 1280., 1320., 1150., 1547., 1310., 1280., 1130.,
         1680.,  845.,  780.,  770., 1035., 1015.,  845.,  830., 1195.,
         1285.,  915., 1035., 1285., 1515.,  990., 1235., 1095.,  920.,
          880., 1105., 1020.,  760.,  795., 1035., 1095.,  680.,  885.,
         1080., 1065.,  985., 1060., 1260., 1150., 1265., 1190., 1375.,
         1060., 1120.,  970., 1270., 1285.,  520.,  680.,  450.,  630.,
          420.,  355.,  678.,  502.,  510.,  750.,  718.,  870.,  410.,
          472.,  985.,  886.,  428.,  392.,  500.,  750.,  463.,  278.,
          714.,  630.,  515.,  520.,  450.,  495.,  562.,  680.,  625.,
          480.,  450.,  495.,  290.,  345.,  937.,  625.,  428.,  660.,
          406.,  710.,  562.,  438.,  415.,  672.,  315.,  510.,  488.,
          312.,  680.,  562.,  325.,  607.,  434.,  385.,  407.,  495.,
          345.,  372.,  564.,  625.,  465.,  365.,  380.,  380.,

In [45]:
target = wineq[:, -1].long()
target

tensor([1065, 1050, 1185, 1480,  735, 1450, 1290, 1295, 1045, 1045, 1510,
        1280, 1320, 1150, 1547, 1310, 1280, 1130, 1680,  845,  780,  770,
        1035, 1015,  845,  830, 1195, 1285,  915, 1035, 1285, 1515,  990,
        1235, 1095,  920,  880, 1105, 1020,  760,  795, 1035, 1095,  680,
         885, 1080, 1065,  985, 1060, 1260, 1150, 1265, 1190, 1375, 1060,
        1120,  970, 1270, 1285,  520,  680,  450,  630,  420,  355,  678,
         502,  510,  750,  718,  870,  410,  472,  985,  886,  428,  392,
         500,  750,  463,  278,  714,  630,  515,  520,  450,  495,  562,
         680,  625,  480,  450,  495,  290,  345,  937,  625,  428,  660,
         406,  710,  562,  438,  415,  672,  315,  510,  488,  312,  680,
         562,  325,  607,  434,  385,  407,  495,  345,  372,  564,  625,
         465,  365,  380,  380,  378,  352,  466,  342,  580,  630,  530,
         560,  600,  650,  695,  720,  515,  580,  590,  600,  780,  520,
         550,  855,  830,  415,  625, 

In [47]:
target_onehot = torch.zeros(target.shape[0], data.shape[0])

target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

RuntimeError: index 1065 is out of bounds for dimension 1 with size 178

In [43]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

tensor([[1065],
        [1050],
        [1185],
        [1480],
        [ 735],
        [1450],
        [1290],
        [1295],
        [1045],
        [1045],
        [1510],
        [1280],
        [1320],
        [1150],
        [1547],
        [1310],
        [1280],
        [1130],
        [1680],
        [ 845],
        [ 780],
        [ 770],
        [1035],
        [1015],
        [ 845],
        [ 830],
        [1195],
        [1285],
        [ 915],
        [1035],
        [1285],
        [1515],
        [ 990],
        [1235],
        [1095],
        [ 920],
        [ 880],
        [1105],
        [1020],
        [ 760],
        [ 795],
        [1035],
        [1095],
        [ 680],
        [ 885],
        [1080],
        [1065],
        [ 985],
        [1060],
        [1260],
        [1150],
        [1265],
        [1190],
        [1375],
        [1060],
        [1120],
        [ 970],
        [1270],
        [1285],
        [ 520],
        [ 680],
        [ 450],
        

In [48]:
data_mean = torch.mean(data, dim=0)
data_mean

tensor([ 1.94, 13.00,  2.34,  2.37, 19.49, 99.74,  2.30,  2.03,  0.36,
         1.59,  5.06,  0.96,  2.61])

In [49]:
data_var = torch.var(data, dim=0)
data_var

tensor([6.01e-01, 6.59e-01, 1.25e+00, 7.53e-02, 1.12e+01, 2.04e+02,
        3.92e-01, 9.98e-01, 1.55e-02, 3.28e-01, 5.37e+00, 5.22e-02,
        5.04e-01])

In [50]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[-1.21,  1.51,  ...,  0.36,  1.84],
        [-1.21,  0.25,  ...,  0.40,  1.11],
        ...,
        [ 1.37,  0.21,  ..., -1.56, -1.40],
        [ 1.37,  1.39,  ..., -1.52, -1.42]])

In [51]:
bad_indexes = target <= 3 # <1>
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([178]), torch.bool, tensor(0))

In [53]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([0, 13])

In [54]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)] # <1>
good_data = data[target >= 7]

bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 Wine                    nan    nan   1.94
 1 Alcohol                 nan    nan  13.00
 2 Malic.acid              nan    nan   2.34
 3 Ash                     nan    nan   2.37
 4 Acl                     nan    nan  19.49
 5 Mg                      nan    nan  99.74
 6 Phenols                 nan    nan   2.30
 7 Flavanoids              nan    nan   2.03
 8 Nonflavanoid.phenols    nan    nan   0.36
 9 Proanth                 nan    nan   1.59
10 Color.int               nan    nan   5.06
11 Hue                     nan    nan   0.96
12 OD                      nan    nan   2.61
