In [1]:
# Based on Stevens et al. Deep learning with PyTorch, Manning Publications Co, 2020

import numpy as np
import torch
import torch.optim as optim

In [2]:
x = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
y = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
x = torch.tensor(x).unsqueeze(1)
y = torch.tensor(y).unsqueeze(1)
x.shape

torch.Size([11, 1])

In [5]:
n_samples = x.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

shuffled_indices, train_indices, val_indices

(tensor([ 1,  0,  2,  9,  4, 10,  7,  8,  5,  3,  6]),
 tensor([ 1,  0,  2,  9,  4, 10,  7,  8,  5]),
 tensor([3, 6]))

In [6]:
x_train = x[train_indices]
y_train = y[train_indices]

x_val = x[val_indices]
y_val = y[val_indices]

xn_train = 0.1 * x_train
xn_val = 0.1 * x_val

In [25]:
import torch.nn as nn

linear_model = nn.Linear(1, 1)
list(linear_model.parameters())

[Parameter containing:
 tensor([[0.6336]], requires_grad=True),
 Parameter containing:
 tensor([-0.2082], requires_grad=True)]

In [26]:
x_try = torch.ones(1)
linear_model(x_try)

tensor([0.4253], grad_fn=<ViewBackward0>)

In [27]:
linear_model(xn_val)

tensor([[4.9806],
        [1.9395]], grad_fn=<AddmmBackward0>)

In [28]:
def loss_fn(yPred, y):
    se = (yPred - y)**2
    return se.mean()

optimizer = optim.SGD(
    linear_model.parameters(),
    lr=1e-2)

In [29]:
def training_loop(n_epochs, optimizer, model, loss_fn, x_train, x_val,
                  y_train, y_val):
    for epoch in range(1, n_epochs + 1):
        yPred_train = model(x_train)
        loss_train = loss_fn(yPred_train, y_train)

        yPred_val = model(x_val)
        loss_val = loss_fn(yPred_val, y_val)
        
        optimizer.zero_grad()
        loss_train.backward()
        optimizer.step()

        if epoch == 1 or epoch % (n_epochs / 10) == 0:
            print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"
                  f" Validation loss {loss_val.item():.4f}")


In [30]:
training_loop(
    n_epochs = 10000, 
    optimizer = optimizer,
    model = linear_model,
    loss_fn = loss_fn,
    x_train = xn_train,
    x_val = xn_val, 
    y_train = y_train,
    y_val = y_val)

print()
list(linear_model.parameters())

Epoch 1, Training loss 82.5363, Validation loss 265.5093
Epoch 1000, Training loss 4.3520, Validation loss 10.1836
Epoch 2000, Training loss 2.8644, Validation loss 5.2006
Epoch 3000, Training loss 2.7437, Validation loss 4.7363
Epoch 4000, Training loss 2.7339, Validation loss 4.6815
Epoch 5000, Training loss 2.7331, Validation loss 4.6721
Epoch 6000, Training loss 2.7331, Validation loss 4.6700
Epoch 7000, Training loss 2.7331, Validation loss 4.6694
Epoch 8000, Training loss 2.7331, Validation loss 4.6693
Epoch 9000, Training loss 2.7331, Validation loss 4.6693
Epoch 10000, Training loss 2.7331, Validation loss 4.6693



[Parameter containing:
 tensor([[5.3212]], requires_grad=True),
 Parameter containing:
 tensor([-17.4537], requires_grad=True)]