# BM40A1401 GPU Computing

## Erik Kuitunen

### Exercise 1

Import needed libraries.

In [1]:
#!pip install pycuda
import pycuda.autoinit
import pycuda.driver as cuda
from pycuda.compiler import SourceModule
import numpy as np

#### Task 1
Implement a kernel which takes two vectors A and B and adds them together to form a vector C.

Derfining the kernel.

In [2]:
modd = SourceModule("""
  __global__ void vector_addition( double* a, double* b, double* c, int n_elem) {

    for ( int i = threadIdx.x + blockIdx.x * blockDim.x; 
          i < n_elem; 
          i += gridDim.x * blockDim.x ) {
            
      c[i] = a[i] + b[i];
    
    }
  }
""")

Create data vectors and initalize thread and block sizes

In [3]:
N = 10 ** 5
a = np.random.randn(N).astype( float )
b = np.random.randn(N).astype( float )

block_dims = ( 1024, 1, 1 )
grid_dims = ( 64, 1, 1 )

Allocate memory to GPU and copy data to device

In [4]:
a_gpu = cuda.mem_alloc( a.size * a.dtype.itemsize )
cuda.memcpy_htod( a_gpu, a )

b_gpu = cuda.mem_alloc( a.size * a.dtype.itemsize )
cuda.memcpy_htod( b_gpu, b )

c = np.empty_like(a)
c_gpu = cuda.mem_alloc( a.size * a.dtype.itemsize )

Calling the CUDA kernel.

In [5]:
kernel = modd.get_function( "vector_addition" )

kernel( a_gpu, b_gpu, c_gpu, np.int32(N), block = block_dims, grid = grid_dims )

Copying the results back to host and verifying the results

In [6]:
cuda.memcpy_dtoh( c, c_gpu )

c_cpu = a + b

if ( c_cpu == c ).all():
    print( "The vectors are the same." )   
else:
    print( "The vector are not the same. Something is wrong." )

The vectors are the same.


#### Task 2

Implement a kernel which multiplies two matrices together.

Defining the kernel

In [7]:
modd = SourceModule("""
  __global__ void matrix_multiplication( const float* A, const float* B, float* C, int M, int N, int K) {
    
    int row = threadIdx.y; 
    int col = threadIdx.x;
    float C_elem = 0;
    
    if ( row > K-1 || col > K-1 ) {
      return;
    }
    
    for ( int ii = 0; ii < N; ++ii ) {
        
      float A_elem = A[ row * N + ii ];
      float B_elem = B[ col + K * ii ];

      C_elem += A_elem * B_elem;
    
    }
    
    C[ col + row * K ] = C_elem;
    
  } 
""")

Create data matrices and initalize thread and block sizes

In [8]:
BLOCK_SIZE = 16

M = 14   # Rows of A and C
N = 15   # Columns of A; rows of B
K = 16   # Columns of B and C

A = np.float32( np.random.rand( M, N ) )
B = np.float32( np.random.rand( N, K ) )

block_dims = ( BLOCK_SIZE, BLOCK_SIZE, 1 )
grid_dims = ( 1, 1, 1 )

Allocate memory and copy data from host to device 

In [9]:
A_gpu = cuda.mem_alloc( A.nbytes )
cuda.memcpy_htod( A_gpu, A )

B_gpu = cuda.mem_alloc( B.nbytes )
cuda.memcpy_htod( B_gpu, B )

C = np.empty( [ A.shape[0], B.shape[1] ], dtype = np.float32 )
C_gpu = cuda.mem_alloc( C.nbytes )


Calling the CUDA kernel.

In [10]:
kernel = modd.get_function( "matrix_multiplication" )

kernel( A_gpu, B_gpu, C_gpu, np.int32(M), np.int32(N), np.int32(K),
        block = block_dims, grid = grid_dims )

Copying the results back to host and verifying the results

In [11]:
cuda.memcpy_dtoh( C, C_gpu )

C_cpu = np.dot( A, B )

C_diff = abs( C_cpu - C )

if ( C_diff.all() < 10 ** -6 ):
    print( "The result matrices are (nearly) the same." )   
else:
    print( "The matrices are not the same. Something is wrong." )

The result matrices are (nearly) the same.


Differences in the order of $ 10^7 $ can be found from the results. Why?




#### Task 3

Extend the kernel from task 2 to use shared memory.

In [12]:
kernel_code_template = """
  __global__ void matmul_sharedmem( const float* A, const float* B, float* C, int M, int N, int K, int n_tiles ) {
    
    float C_elem = 0;
    
    // Block indices, each block computes submatrix of C, C_sub
    int block_row = blockIdx.y;
    int block_col = blockIdx.x;
    
    // Thread indices. Each thread computes an element of C_sub
    int thread_row = threadIdx.y;
    int thread_col = threadIdx.x;

    // Looping through relevant submatrices to compute C_sub
    for (int ii = 0; ii < n_tiles; ++ii ) { 
    
      // Loading submatrices from global memory
      int linear_ind_A = N * thread_row + thread_col + ii * %(TILE_WIDTH)s + block_row * %(TILE_WIDTH)s * N;
      int linear_ind_B = K * thread_row + thread_col + ii * %(TILE_WIDTH)s * K + block_col * %(TILE_WIDTH)s;
      
      // Shared memory for the submatrices of A and B
      __shared__ float A_sub[ %(TILE_WIDTH)s ][ %(TILE_WIDTH)s ];
      __shared__ float B_sub[ %(TILE_WIDTH)s ][ %(TILE_WIDTH)s ];
      
      // TODO check for threads outside matrix bounds
      
      A_sub[ thread_row ][ thread_col ] = A[ linear_ind_A ];
      B_sub[ thread_row ][ thread_col ] = B[ linear_ind_B ];
      
      __syncthreads();
      
      // Doing the actual multiplication of the submatrices
      for (int kk = 0; kk < %(TILE_WIDTH)s; ++kk) {
        
        float A_sub_elem = A_sub[ thread_row ][ kk ];
        float B_sub_elem = B_sub[ kk ][ thread_col ];
        
        C_elem += A_sub_elem * B_sub_elem;
        
      }
      
      __syncthreads();
    
    }
      
    // Saving the C_elem to matrix C
    int linear_ind_C = block_row * %(TILE_WIDTH)s * K + block_col * %(TILE_WIDTH)s + thread_row * K + thread_col;
    C[ linear_ind_C ] = C_elem;
    
  } 
"""

Create data vectors and initalize thread and block sizes

In [13]:
TILE_WIDTH = 4

M = 4
N = M
K = M

testarr1 = np.array( [1, 1, 1, 1], dtype = np.float32 )
testarr2 = np.array( [1, 2, 3, 4], dtype = np.float32 )
A = np.array( [ 1*testarr1, 2*testarr1, 3*testarr1, 4*testarr1 ] )
B = np.array( [ testarr2, testarr2, testarr2, testarr2 ] )

A = np.float32( np.random.rand( M, N ) )
B = np.float32( np.random.rand( N, K ) )

gridDim = int( N/TILE_WIDTH )
block_dims = ( TILE_WIDTH, TILE_WIDTH, 1 )
grid_dims = ( gridDim, gridDim, 1 )

Allocate memory and copy data from host to device 

In [14]:
A_gpu = cuda.mem_alloc( A.nbytes )
cuda.memcpy_htod( A_gpu, A )

B_gpu = cuda.mem_alloc( B.nbytes )
cuda.memcpy_htod( B_gpu, B )

C = np.empty( [ A.shape[0], B.shape[1] ], dtype = np.float32 )
C_gpu = cuda.mem_alloc( C.nbytes )

Specify constant TILE_WIDTH for the kernel. Compile and call the kernel.

In [15]:
kernel_code = kernel_code_template % {
        'TILE_WIDTH': TILE_WIDTH
        }

# Compile the kernel code
mod = SourceModule( kernel_code )

matrixmul = mod.get_function( "matmul_sharedmem" )

matrixmul( A_gpu, B_gpu, C_gpu, np.int32(M), np.int32(N), np.int32(K), np.int32(2),
          block = block_dims, grid = grid_dims )

C:\Users\erikk\AppData\Local\Temp\ipykernel_85592\4285599408.py:6: UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu

  mod = SourceModule( kernel_code )


Copying the results back to host and verifying the results

In [16]:
cuda.memcpy_dtoh( C, C_gpu )

C_cpu = np.dot( A, B )

print("CPU: ")
print( C_cpu)

print( "\nGPU: ")
print( C )

C_diff = abs( C_cpu - C )
print( "\nDifference: ")
print( C_diff )

if ( C_diff.all() < 10 ** -6 ):
    print( "The result matrices are (nearly) the same." )   
else:
    print( "The matrices are not the same. Something is wrong." )

CPU: 
[[1.5832738 1.5238987 1.2237086 1.2037269]
 [1.8890549 1.8417578 1.4358554 1.2525882]
 [1.0521787 1.0985444 0.6182429 0.5691301]
 [1.4388049 1.3882624 1.0331012 1.3743474]]

GPU: 
[[3.0828373 3.1578813 2.4912577 2.577466 ]
 [2.660978  2.5740016 2.6157286 2.259741 ]
 [2.2543457 2.4981287 1.5489715 1.6419407]
 [1.4388049 1.3882624 1.0331012 1.3743474]]

Difference: 
[[1.4995636 1.6339825 1.267549  1.3737391]
 [0.7719232 0.7322438 1.1798732 1.0071529]
 [1.2021669 1.3995843 0.9307286 1.0728106]
 [0.        0.        0.        0.       ]]
The result matrices are (nearly) the same.


Once again differences are appearing. Seems to be related to the ratio of the size of matrix and tile width?