### NumPy datatypes (dtypes)
https://note.nkmk.me/en/python-numpy-dtype-astype/

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([1.0,2.0,3.0])

print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64


In [4]:
a = np.array([1,2,3], dtype=np.int32)
print(a.dtype)

int32


### (Explicit) data conversion

How to change the data type

In [6]:
b = np.array([1.0,2.0,3.0])
print(b)
print(b.dtype)

[1. 2. 3.]
float64


In [7]:
b = b.astype('int32')
print(b)
print(b.dtype)

[1 2 3]
int32


In [8]:
b = b.astype('float16')
print(b)
print(b.dtype)

[1. 2. 3.]
float16


What happens if you reduce the number of bits, for example from 64 to 8.

In [9]:
b = np.array([16,64,264])
print(b)
print(b.dtype)

[ 16  64 264]
int64


In [10]:
b = b.astype('int8')
print(b)
print(b.dtype)

[16 64  8]
int8


As you can see. Some data got lost. So be carefull.


How about quickly convert to int64

In [11]:
b = b.astype('int64')
print(b)
print(b.dtype)

[16 64  8]
int64


No luck!

### Implicit type conversion

Sometimes NumPy makes data conversions by itself. Be mindfulll about these also.

In [12]:
a = np.array([1,2,3])
print(a)
print(a.dtype)

[1 2 3]
int64


In [13]:
print((a * a).dtype)

int64


In [14]:
print((a ** 2).dtype)

int64


In [15]:
print((a / 1).dtype)

float64


In [16]:
print((a + 1).dtype)

int64


In [17]:
print((a + 1.0).dtype)

float64


### Data type sizes
How many Bytes our values need.

In [18]:
a = np.array([1,2,3], dtype=np.int64)
print(a.dtype)

int64


In [19]:
print(a.dtype.itemsize)

8


In [21]:
a = a.astype(float)
print(a.dtype)
print(a.dtype.itemsize)

float64
8


In [22]:
a = a.astype(int)
print(a.dtype)
print(a.dtype.itemsize)

int64
8


### NumPy dtype infos

In [24]:
print(np.iinfo(np.int32))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------



In [25]:
print(np.iinfo(np.int64))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [26]:
print(np.iinfo(np.uint32))

Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------



In [27]:
print(np.finfo(np.float32))

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



In [28]:
print(np.finfo(np.float64))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------

